
gem 'catalogillo', path: '../../'

gem 'bootstrap-sass', '>= 2.3'

gem 'kaminari'

gem "jquery-rails"

gem "sunspot_rails", ">= 2.0"

gem "multi_fetch_fragments"

gem 'versionist', '>= 1.0'

gem 'pry'

gem 'unicorn'
